format_version: 3
pipelines:
  build:
    environment_variables:
    materials:
      git:
        git: https://github.com/pprach/gotest.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build_image:
            timeout: 0
            elastic_profile_id: my
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t .
                command: /bin/bash
                run_if: passed